# display size in pixels
DISPLAY_SIZE_HORIZONTAL = 500
DISPLAY_SIZE_VERTICAL = 500

# number of tiles
HORIZONTAL_TILES_NUMBER = DISPLAY_SIZE_HORIZONTAL/20
VERTICAL_TILES_NUMBER = DISPLAY_SIZE_VERTICAL/20


#colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)

#tractor const
TRACTOR_HORIZONTAL_LOCATION = DISPLAY_SIZE_HORIZONTAL/2
TRACTOR_VERTICAL_LOCATION = DISPLAY_SIZE_VERTICAL/2

TRACTOR_WIDTH = DISPLAY_SIZE_HORIZONTAL/20
TRACTOR_HEIGHT = DISPLAY_SIZE_VERTICAL/20

#FRAMES PER SECOND
FPS = 144




